/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.quanlysinhvien.main.controllers;

import com.quanlysinhvien.main.model.Lop;
import com.quanlysinhvien.main.model.LopRepository;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

/**
 *
 * @author locng
 */
@Controller
public class HomeController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private LopRepository lopRepository;

    @RequestMapping("/")
    public String home(Model model) {
        List<Lop> ds = (List<Lop>) lopRepository.findAll();
        model.addAttribute("classes", ds);
        return "home";
    }
}
