/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.quanlysinhvien.main.controllers;

import com.quanlysinhvien.main.model.Lop;
import com.quanlysinhvien.main.model.LopRepository;
import com.quanlysinhvien.main.model.SinhVien;
import com.quanlysinhvien.main.model.SinhVienRepository;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

/**
 *
 * @author locng
 */
@Controller
public class SinhVienController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SinhVienRepository sinhVienRepository;

    @RequestMapping("/sinhvien")
    public String listSinhVien(Model model) {
        List<SinhVien> ds = (List<SinhVien>) sinhVienRepository.findAll();
        model.addAttribute("students", ds);
        return "sinhvienview";
    }

//    @RequestMapping(value = "/addclass", method = RequestMethod.POST)
//    public String saveClass(@RequestParam String classname,
//             Model model) {
//        // lopRepository.find
//        Lop lop = new Lop();
//        lop.setTenlop(classname);
//        sinhVienRepository.save(lop);
//        return "redirect:/";
//    }
//
//    /**
//     *
//     * @param classID
//     * @return
//     */
    @PostMapping("/deletesv")
    public String deleteStudent(@RequestParam String studentID) {
        SinhVien sv = sinhVienRepository.findById(studentID);
       sinhVienRepository.delete(sv);
        return "redirect:/sinhvien";
    }
}
